# A docker compose file simply use for creating and running a contianer of postgress
# database will always restart
# database memory will be mount to the local machine so that after restart the data will not be lost
# database will be running on port 8080
# database will be running on the background
# databasw will be running on user & password
# compose fill will fetch the user and password from the .env file

version: '3.9'

services:
    db:
        image: postgres
        restart: always
        container_name: postgress_memovortex_backend
        shm_size: 128mb
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./db_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        #volumes:
        #  - type: tmpfs
        #    target: /dev/shm
        #    tmpfs:
        #      size: 134217728 # 128*2^20 bytes = 128Mb

    # adminer is a database management tool that allows you to manage content in your database
    # so remember to remove it in production
    # adminer:
    #   image: adminer
    #   restart: always
    #   ports:
    #     - 8080:8080
